---
# tasks file for mapr_hive_test

- name: run a minimal hive command
  run_once: yes
  sudo_user: mapr
  command: hive -e 'show tables'
  changed_when: False

- name: load some data into hive and select
  run_once: yes
  sudo_user: mapr
  command: hive -e "CREATE TABLE IF NOT EXISTS pokes (foo INT, bar STRING); LOAD DATA LOCAL INPATH '/opt/mapr/hive/hive-1.0/examples/files/kv1.txt' OVERWRITE INTO TABLE pokes; SELECT * FROM pokes;"
  changed_when: False

- name: drop pokes table
  run_once: yes
  sudo_user: mapr
  command: hive -e 'DROP TABLE pokes;'

